<?php
// 定義錯誤代碼
$SUCCESS_ENROLLMENT    = 1;
$EMPTY_INPUT_DATA     = 2;
$USED_USERNAME        = 3;
$ACCOUNT_NOT_FOUNDED  = 4;
$EMPTY_COMMENT        = 5;
$PASSWORD_NOT_FOUNDED = 6;
$EMPTY_NICKNAME       = 7;
$INVALID_OPERATION    = 8;
$SUCCESS_EXEC_DELETE  = 9;
$SUCCESS_UPDATE_CONTENT = 10;
$SUCCESS_ADD_COMMENT    = 11;
$SUCCESS_UPDATE_NICKNAME = 12;
$ERROR_SERVER_SIDE    = 9999;
?>